project:
  type: book
  execute-dir: project
  
book:
  title: "Deep Learning for Investigating Causal Effects with High-Dimensional Data: Analytic Tools and Applications to Educational Interventions"
  author: "Alberto Guzman-Alvarez"
  output-file: "alberto_guzmanalvarez_diss"
  date: last-modified
  date-format: long
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-propensity_over.qmd
    - 03-commonapp_over.qmd
    - references.qmd
    
bibliography: m3m4.bib
csl: apa.csl
link-citations: yes


format: 
  titlepage-pdf:
    documentclass: report
    geometry: margin=1.0in
    fontsize: 12pt
    toc-depth: 3
    number-sections: TRUE
    toc: TRUE
    lof: TRUE
    lot: TRUE
    titlepage: plain


    