project:
  type: book
  execute-dir: project

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "Diss Title"
  author: "Alberto Guzman-Alvarez"
  output-file: "alberto_guzmanalvarez_diss"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-propensity_over.qmd
    - 03-commonapp_over.qmd
    - simulation_code.qmd
    - references.qmd

bibliography: "https://api.citedrive.com/bib/a3b2d1f7-6632-4857-8038-c222a4053fa1/references.bib?x=eyJpZCI6ICJhM2IyZDFmNy02NjMyLTQ4NTctODAzOC1jMjIyYTQwNTNmYTEiLCAidXNlciI6ICIyMDQxIiwgInNpZ25hdHVyZSI6ICI4MDNmNDRkNGI0ZGFlNzlhMThhMDEwZjAwYTUxN2QzOTQ1YzUxYTc5Y2QxMzc5OGQ2OGJjOTIyZmEwOGFkODJiIn0=/bibliography.bib"
csl: apa.csl

format:
  pdf:
    documentclass: book
    classoption: ["oneside", "open=any"]
    margin-left: "1in"
    margin-right: "1in"
    margin-top: "1in"
    margin-bottom: "1in" 
    linestretch: 2
    template-partials: 
      - "tex/before-body.tex" 
      - "tex/_titlepage.tex" 
      - "tex/toc.tex" 
    include-in-header: 
      - text: | 
         \usepackage{indentfirst}
         \setlength{\parindent}{1cm}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
         \usepackage{setspace}
         \doublespacing
         \pagenumbering{gobble} 
         \usepackage{sectsty}
         \chapterfont{\fontsize{12}{15}\selectfont\centering\bfseries}
         \sectionfont{\fontsize{12}{15}\selectfont\centering\bfseries}
         \subsectionfont{\fontsize{12}{15}\selectfont\centering\bfseries}
         \subsubsectionfont{\fontsize{12}{15}\selectfont\centering\bfseries}
         \usepackage{tocloft}
         \renewcommand{\cftchapaftersnum}{.0}
         \setlength{\cftchapnumwidth}{2.5em}
         \renewcommand{\contentsname}{\centering\Large\bfseries Table of Contents}
         \renewcommand{\cfttoctitlefont}{\hfill\Large\bfseries}
         \renewcommand{\cftaftertoctitle}{\hfill\null}
         \renewcommand{\cftlottitlefont}{\hfill\Large\bfseries}
         \renewcommand{\cftafterlottitle}{\hfill\null}
         \renewcommand{\cftloftitlefont}{\hfill\Large\bfseries}
         \renewcommand{\cftafterloftitle}{\hfill\null}
         \usepackage{etoolbox}
         \makeatletter
         \patchcmd{\l@chapter}{\numberline{\thechapter}}{\numberline{\thechapter.0\hspace{0.25em}}}{}{}
         \makeatother
           
    toc: true
    toc-depth: 4
    lot: true
    lof: true
    number-sections: TRUE

