project:
  type: book

book:
  title: "alberto_m3_m4"
  author: "Alberto Guzman-Alvarez"
  chapters:
    - index.qmd
    - intro.qmd
    - lit_review.qmd
    - part: current_studies.qmd
      chapters: 
        - commonapp_over.qmd
        - propensity_over.qmd
    - conclusions.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  
