project:
  type: book
  execute-dir: project


book:
  title: "Dissertation Proposal"
  subtitle: "Deep learning for investigating causal effects with high-dimensional data: analytic tools and applications to educational interventions"
  author: "Alberto Guzman-Alvarez, M.A."
  date: today
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - lit_review.qmd
    - part: current_studies.qmd
      chapters: 
        - commonapp_over.qmd
        - propensity_over.qmd
    - conclusions.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: report
    
geometry: margin=1.0in
font-size: 12pt
header-includes:
 - \usepackage{helvet}
 - \renewcommand*\familydefault{\sfdefault}
 
 