project:
  type: book
  execute-dir: project

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "Diss Title"
  author: "Alberto Guzman-Alvarez"
  output-file: "alberto_guzmanalvarez_diss"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-propensity_over.qmd
    - 03-commonapp_over.qmd
    - references.qmd
    - simulation_code.qmd
    
bibliography: m3m4.bib
csl: apa.csl
link-citations: yes

format:
  pdf:
    documentclass: book 
    # class option “oneside” makes the margins of the even and odd pages 
    # the same. 
    # class option “open=any” allows chapters and parts to start
    # on even or odd pages; the default is to only start chapters and parts
    # on odd pages. 
    # class option "listof=totoc" adds the list of tables and list of figures to TOC
    # https://tex.stackexchange.com/questions/48509/insert-list-of-figures-in-the-table-of-contents
    classoption: ["oneside", "open=any", "listof=totoc"]
    margin-left: "1in"
    margin-right: "1in"
    margin-top: "1in"
    margin-bottom: "1in" # this is larger than technically needed, but it gets the page number in the footer >1in from the bottom (a requriement per UMN)
    linestretch: 1.5
    template-partials: 
      - "tex/before-body.tex" # overrides default template used by quarto
      - "tex/_titlepage.tex" # custom title page
    include-in-header: 
      - text: | 
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
          \usepackage{setspace}
          \doublespacing
          \pagenumbering{gobble} 
    include-before-body: 
      - file: "tex/copyright.tex"
      - file: "tex/acknowledgements.tex"
      - file: "tex/dedication.tex"
      - file: "tex/abstract.tex"
    toc: true
    toc-depth: 3
    lof: true
    lot: true
    number-sections: TRUE
  docx:
    toc: true
    reference-doc: custom-reference.docx