## AI-bot nudge intervention for college access during COVID-19

### Introduction






### COVID-19 college access

The COVID-19 pandemic has disrupted the lives of millions worldwide. 



### College access

We take a anti-deficit appraoch to our grounding of first-generation, low-income students, many of which are studens of color. Anti-deficit approaches explore how marginalized students persist in the face of social and structural barriers (Harper, 210). The goal is to reframe students' experiences from struggling to ones of serielincty, since most deficit aporahes focus on what students lacks, anti-deficit approahces focus on what student bring that leads to their relienacy and persistance. 


### College access nudges

Results are mixed on the effectiveness of nudge interventions. Overall, studies that have more "personalized" approaches to the intervention do well than studies with a remote counselor. Certain topics are more engaged for example
#### Low-touch


#### High-touch



### AI-bots in college access

















### CommongApp

### Propensity Score

### Summary of Literature Review

