---
title: "For Lindsay Review"
---

# Paper 2: When in-person support is not possible, can virtual outreach help? Evaluating the impact of an artificially intelligent conversational chatbot to promote college enrollment during the COVID-19 pandemic

## Introduction

In spring 2020, schools and colleges across the US began to shut down and pivot to remote learning to protect students and their communities from the rapid spread of the COVID-19 virus. At the same time, high school seniors who had applied to college before the pandemic began receiving acceptance notifications, even though the pandemic's impact on college enrollment was unknown. On the one hand, the COVID-19 crisis hampered business-as-usual operating procedures for colleges. As a result, students, particularly those planning to live on campus during college, may have been more likely to postpone their college enrollment. On the other hand, higher education is a counter-cyclical industry, such that college enrollment rates tend to be higher during economic downturns. For recent high school graduates, the impact of the pandemic on the retail and service sectors severely limited job opportunities. By April 2020, the unemployment rate in the United States reached 14.5% – the highest rate recorded in recent history – with the service and retail sectors experiencing the bulk of job losses. (US Bureau of Labor Statistics, 2021). As a result, college may have become more appealing to young adults who would otherwise enter the workforce after high school.

To address this uncertainty, the Common Application (Common App), a non-profit organization dedicated to assisting students with college applications, partnered with Mainstay, an EdTech company focused on using behavioral intelligence for college access, and the College Advising Corps (CAC), a non-profit that places recent college graduates as college counselors in underserved high schools. These partnered organizations acted quickly to provide students with proactive outreach and guidance on college-going tasks through an innovative, large-scale chatbot campaign. This outreach targeted around 174,000 US high school students who were the first in their families to attend college and came from low-income families. The majority (83%) of these students were also racially marginalized. Due to various systemic barriers, this subset of students were disproportionately likely to have had limited access to quality health care, living, and working conditions during the pandemic (CITE). Additionally, this group of students were less likely to have ready access to personalized college-going guidance and potentially stood to benefit from additional support during their precarious college transition.

Over 38 weeks, an artificially intelligent (AI) chatbot named *Oli* sent students scripted messages on various college search, application, and enrollment-related topics. The scripted messages were developed by individuals at the Common App in collaboration with CAC and included messages reminding students about upcoming deadlines, such as “Hey <STUDENT NAME>, #CollegeSigningDay is this Friday, May 1st. Have you decided what school you’re going to attend?” To better target the information, Oli solicited information directly from students about the types of resources they needed and pressing questions they had. The chatbot “learned” how to interact with students by first having staff at the partnered organizations seed the chatbot with frequently asked questions and answers. As Oli interacted with students, it built an ever-increasing knowledge base for student questions that aided the chatbot in providing more targeted and individualized real-time responses. As the intervention rolled out, Common App and CAC staff could monitor interactions and correct and add to Oli’s knowledge base.
Student questions that Oli could not answer were forwarded to college advisers at the CAC, who would follow up directly with individual students.

In recent years, researchers have developed an interest in understanding how insights from behavioral economics can inform strategies to support students to and through college (CITE). Several of these studies have involved designing and testing proactive communication strategies using text messaging as the primary mode of communication (CITE). Recent studies have investigated text messaging communication employing artificially intelligent chatbot capability. These studies have demonstrated that chatbots can be effective in assisting students to complete pre-matriculation tasks and enroll in college (Page..Gelbach..Aizat, 2017; 2020; 2021). However, there are numerous open questions regarding the scalability of these chatbot interventions. Text nudge interventions have mixed results when implemented at scale, with many studies finding minimal to no effects on college-related outcomes (Bird et al. DATE). 

Therefore, my second dissertation study aims to contribute to the literature on the scalability of chatbot interventions by evaluating the large-scale chatbot campaign implemented by the Common App, College Advising Corps, and Mainstay aimed at low-income, first-generation students. Specifically, I investigate whether the college applications and enrollment rates were higher among students targeted for this chatbot outreach compared to their observationally similar peers who were not targeted. In addition, I examine treatment heterogeneity based on students' application behavior, racial/ethnic identity, and the level of chatbot engagement.

The remainder of this document is structured as follows:  First, I review the relevant literature for this study. Then, I describe the data and my analytic approach. Finally, I conclude with a discussion of preliminary findings.

## Literature Review

In this section, I review the literature on college access in general as well as during the COVID-19 pandemic. In addition, I draw on literature examining how behavioral text message nudge interventions and chatbots can assist high school students in overcoming obstacles to college access.

Before reviewing the literature, I first define how I conceptualize first-generation students – students whose parents do not have any postsecondary education experience – and the systemic barriers they face in college access. I take an anti-deficit approach to my grounding of first-generation students -- many of whom also tend to be economically and racially marginalized (CITE). Anti-deficit practices explore how marginalized students persist in the face of social and structural barriers (CITE, Harper) to reframe students' experiences from ones of struggling to ones of resiliency. Since most deficit approaches focus on what students lack, anti-deficit strategies focus on what students bring that leads to their resilience and persistence. Although I take an anti-deficit stance in my review of the literature, I recognize that the majority of the existing literature on college access, especially that focuses on economically and racially marginalized students, is written from a deficit perspective (CITE).

We must acknowledge the structural and social barriers that lead to disparate postsecondary outcomes for first-generation students. For example, economically and racially marginalized individuals face structural barriers to accessing quality education, housing, and employment conditions (CITE). Decades of federal redlining in housing and the policy of using local taxes to fund schools, for instance, produce racial and socioeconomic disparities in educational opportunities and family wealth (CITE). In addition, racially marginalized students face social and systemic barriers and federal policies that have historically limited their access to high-quality primary and secondary education (CITE). For example, policies that funnel racially marginalized students into underserved schools with limited access to college prep courses, and school tracking policies that exclude racially marginalized students from gaining access to the college prep tracks that would qualify them to apply to college (Oakes, 2005; Oakes, Rogers, Lipton, & Morell, 2002; Solorzano & Ornelas, 2002, 2004). As a result, disparities in college access and completion based on parental education, as well as social and structural barriers, are significant contributors to the rising income inequality in the US.

### College access and returns to a college education

Despite increased access to higher education over the past several decades, disparities remain in college attainment by socioeconomic status and parental education (CITE). Students whose parents have a college degree are more likely to attend college than those whose parents did not complete high school (CITE). Moreover, students from higher-income backgrounds are more likely to enroll and complete postsecondary education than students from lower-resourced families (CITE). By age 24, roughly 13% of students from the lowest family income quartile earn a bachelor's degree, compared to 64% of students from the highest quartile (Cahalan et al., 2021). 

Despite the rising cost of higher education (CITE), the non-pecuniary and long-term economic returns to a college education remain positive. Adults with a bachelor's degree typically earn and accumulate more wealth than those without a degree (CITE). Higher education is associated with lower unemployment rates, greater civic engagement, and better health outcomes (CITE). Yet, the rate of economic return is higher for continuing education students – students whose parents had some postsecondary education experience – than for first-generation students (CITE). Given that more than half of college students identify as first-generation (56%), substantial policy efforts have focused on helping first-generation college-bound students enroll in college (CITE). However, the COVID-19 pandemic introduced unprecedented complexity to these efforts and substantially hindered college access for first-generation students. 

### College access during the COVID-19 pandemic

The COVID-19 pandemic added uncertainty to the lives of high school seniors planning to attend college in the fall of 2020. In the early stages of the pandemic, one in every six recent high school graduates reconsidered enrolling in college, and nearly two-thirds expressed reservations about attending their first choice institution (CITE). The most frequently cited reason for not enrolling at their first-choice institution (CITE) was concern about their family's ability to pay for college.

Now, nearly three years into the pandemic, the adverse effects of the pandemic on college enrollment have become clear. Enrollment for first-time undergraduates fell to historic lows in fall 2020, falling nearly 10 percentage points from fall 2019, with lower immediate college enrollment rates for students from low-income schools compared to high-income schools, where low-income schools are defined as schools where at least 50 percent of the students are eligible for free or reduced-price lunch (CITE). Furthermore, students from low-minority schools were more likely to enroll in college right away than those from majority-minority high schools, defined as schools where at least 40 percent of students are Black or Latinx (CITE).

A recent report from the College Board provides additional information about the detrimental effects of the pandemic on college enrollment. Using data from nearly 10 million US students, the College Board calculated high-level descriptives and regression-adjusted models to determine the proportion of fall 2020 enrollment rates attributable to COVID-19. As a result of the pandemic, enrollment rates at community colleges decreased by roughly 12 percentage points. Most concerning is the decline in enrollment rates among first-generation, low-income students (CITE).

The decline in college enrollment rates for first-generation students is likely a result of the pandemic's disproportionate impact on racially and economically marginalized communities. During the pandemic, these communities experienced reduced access to high-quality healthcare and working conditions and lowered expected wages (CITE). Prior to the pandemic, the average Black and Latino household had a net worth of approximately $17,000, while the average White household held $171,000 (CITE). As a result, Black and Latino households may have had a more challenging time adjusting to the economic shock caused by the pandemic (CITE). These households, on average, have fewer liquid assets and wealth to cover unexpected expenses and wage loss (Center for American Progress, 2021). This may have resulted in first-generation students – notably racially marginalized students –  prioritizing immediate health and economic stresses, such as supporting their families financially or dealing with lost wages, over college enrollment. Indeed, students from higher-income households were far more likely to enroll in college immediately after graduation (65%) than those from low-income high schools (49%). Furthermore, first-generation students were nearly twice as likely to be concerned about paying for education expenses in fall 2020 than continuing education students (CITE). In sum, there has been an unprecedented change in college enrollment caused by the COVID-19 pandemic, particularly for first-generation, economically, and racially marginalized students. Next, I review the literature on well-documented challenges to college access.

### Challenges in college access 

First-generation students face many barriers during the college application, financing, and enrollment processes (CITE). To apply for college, students must complete several complex tasks, including creating a list of colleges, deciding which colleges to apply to, and applying for financial aid via a time-consuming financial aid application (the Free Application for Federal Student Aid - FAFSA). Students typically obtain federal, state, and grant aid – aid that does not have to be repaid – by completing the FAFSA form, which contains over 100 questions about the students' and their families' financial assets. Several behavioral nudge interventions have demonstrated that proactive outreach to students in completing the FAFSA increases college enrollment (CITE). Assisting students with FAFSA submission is only half the battle. The FAFSAs of a subset of first-generation and low-income students are selected for additional scrutiny through a federal auditing system, leading to lower college enrollment rates among low-income, first-generation students (CITE). Additional obstacles remain once a student accepts a college admission offer, notably during the summer before college.

The summer before college enrollment is fraught with additional obstacles to college enrollment (CITE), given that students must complete a number of pre-matriculation administrative tasks before stepping foot on campus, such as submitting high school transcripts, determining which and how much financial aid to accept, taking placement exams, and successfully enrolling in courses (CITE). If students fail to complete these steps, they may ultimately fail to enroll in college, a process termed "summer melt" (CITE). Summer melt affects 10 to 20 percent of all college-bound high school students, with higher rates for first-generation, racial, and economically marginalized students (CITE). Students who, due to an array of systemic barriers, have reduced access to information and support to help them navigate these administrative tasks.

### Unique challenges in college access among first-generation students

For first-generation students with limited family or school-based resources that can facilitate the college application process, navigating these pre-matriculation tasks adds an additional layer of complexity. Moreover, these students must navigate the transition to college while balancing work and family obligations (CITE). First-generation students are more likely to attend schools with fewer college prep or Advanced Placement (AP) courses, which have been linked to higher college enrollment (CITE). Additionally, first-generation students are more likely to attend schools with limited or no access to college counselors, who could assist students with completing college applications and navigating the complex financial aid process (CITE). Nevertheless, even when students *do* have access to a college counselor, these counselors often manage high caseloads and cannot provide individualized support to students who would benefit the most (CITE). Therefore, many scholars have focused on developing interventions focused on assisting these students with pre-matriculation tasks by providing access to individualized advising from a professional college counselor  (CITE).

### Importance of college advising 

A large body of work has been conducted to assess the efficacy of behavioral interventions designed to assist students in meeting the key steps and deadlines required to enroll in college. One favored approach is to deliver targeted information about the college-going process to students through “low-touch” efforts such as proactive text-based outreach or “high-touch” face-to-face college advising. Access to college advising can positively affect college enrollment and persistence (CITE). Castleman et al. (2012) provide one of the earliest pieces of evidence of the positive impact of providing proactive outreach and support around key college-going tasks to low-income students during the summer prior to college. Using a randomized trial, Castleman et al. demonstrate that access to “college-transition” counselors during the summer before college increases students' immediate college enrollment by 14 percentage points. These counselors supported students in reviewing financial aid packages, addressing gaps in the aid they were offered, and completing required pre-matriculation paperwork. One limitation of this study was that only "choice" schools were included in their sample. Therefore, questions remained unanswered as to whether this support was generalizable to public schools.

A follow-up study by Castleman, Page and Schooley (2014) provided evidence of the generalizability of counseling support in public schools. The researcher conducted two college counseling interventions with large urban public school districts that were more nationally representative in Boston and Fulton County, Georgia. Like Castleman et al. 2012 the study provided high school seniors with college counseling support in the summer before college. For example, counselors helped students develop a list of personalized tasks they needed to complete to enroll in college in the fall. Counselors communicated with students using various modalities, including in-person, text, phone, and email. Students who received proactive college counseling in the summer before college increased their college enrollment by 8 to 12 percentage points among low-income students. In the context of a global pandemic, access to college counseling services were severely impacted.

According to Naughton (2021), the pandemic exacerbated pre-existing "cracks" in the ability to provide students with advising services, transforming them into "craters." This is primarily due to high schools shifting from in-person to virtual advising. College advisors felt ineffective in providing virtual support and guidance once high schools transitioned to virtual advising. Advisors' ability to contact students was severely limited, leaving students without support to help them transition to college (CITE). Naughton explains that advisers in high schools with higher college enrollment rates were significantly less affected than those in high schools with lower college enrollment rates, i.e., the students who required the most assistance (CITE). Therefore, strategies that bring virtual proactive outreach and support around critical college-going tasks directly to students who require it most have the potential to improve college-going outcomes for students in these settings.

### Behavioral nudge interventions 

Behavioral nudge interventions have proven to be a low-cost means of providing college students with counseling support (CITE). These interventions condense complex information and deadlines into brief, to-the-point messages that are delivered to students via a familiar mode of communication -- text messages (CITE). In the context of college access, these studies have focused on preventing "summer melt" by assisting students with well-defined but complex tasks such as submitting financial aid applications, submitting high school transcripts, and registering for classes (CITE).

Castleman and Page (DATE) have conducted several randomized controlled studies utilizing informational text nudges to remedy summer melt. For instance, Castleman and Page (2015) use a personalized text message campaign that reminds students about key college-related tasks required to enroll in their receiving college institution. In addition to reminders, students were invited to request follow-up support from a counselor via text message. The text message campaign increased college enrollment by approximately 7 percentage points among students with limited access to college access supports. The low-cost nature of these interventions has increased interest in their use over the past decade (CITE). Recent studies have investigated the scalability of text nudge interventions, with findings that have been much more mixed. A recent study by Bird et al. (2021) suggests that nudges may fail when scaled up. Bird and colleagues investigated student nudges using multiple modalities, such as email and text messages, to encourage students to complete the FAFSA and enroll in college. This study is unique because it targeted nearly 800,000 students across the US who used the Common Application or the Texas admission system. No form of outreach (email or text message) increased financial aid receipt, college enrollment, or persistence. One possible explanation for this finding is that scaling nudge campaigns can be difficult when implemented by a large organization, such as the Common App, because students may lack a personal connection to a large organization, as opposed to their local high school. In order to deliver nudges to a large number of students, the authors suggest that the messaging may be too "generic and one-way" and lack personalization, resulting in students not taking actionable steps to enroll in college. 

In a recent working paper, Page et al. (2022) hypothesize what factors may contribute to the (in)effectiveness of informational text-based nudges in the college access space. One of their primary arguments is that students may be more receptive to text-based nudging when the messaging focuses on tasks and processes that are time-sensitive and have real consequences if not completed, such as resolving a registration hold. In addition, they provide more nuance to the claim made by Bird et al. (2021) that student messaging needs to be personalized to be salient to students. The ostensible sender of the messaging matters. Students may be more receptive to outreach and communication delivered by organizations or individuals that students know and trust (Debnam, 2017; Page et al., 2020). Recent studies have utilized technological advancements to help bridge this personalization gap. 

###  Chatbots in college access

Recent efforts in the literature on behavioral nudges have focused on utilizing artificial intelligence (AI) chatbots to provide personalized assistance to students navigating college applications and enrollment. These conversational chatbots can provide students with personalized information about deadlines and answers to specific questions about the college application process. These bots are trained by college staff to develop a "database" of answers to frequently asked questions regarding college attendance. Over time, the chatbot "learns" how to respond to a broader range of student questions. Once trained and deployed successfully, the chatbot can assist students with answering questions about vital college-going tasks and requirements. 

To date, three empirical studies have demonstrated the effectiveness of chatbots on college access (CITE). The first of these studies was conducted by Page and Gelbach (2017) at Georgia State University (GSU). Page and Gelbach collaborated with GSU and an ed-tech startup (Mainstay; formerly AdmitHub) to develop "Pounce," a conversational chatbot. Pounce assisted students accepted to GSU with navigating pre-matriculation tasks. The chatbot outreach led to a 3.3 percentage point increase in timely enrollment at GSU and helped students with pre-matriculation tasks like signing up for orientation.

A follow-up study at GSU (Page et al., 2022) shifted the focus of the chatbot outreach from helping students enroll at GSU to supporting them once they arrived at GSU by assisting them in completing tasks such as resolving registration holds and seeking campus-based resources (CITE). A novel aspect of this randomized study was its focus on the main campus of GSU-Atlanta, a four-year university, and the Perimeter campus of GSU, a two-year college. The chatbot effectively changed student behavior regardless of institution type when outreach addressed serious and time-sensitive administrative processes, such as resolving registration holds (CITE). In contrast, outreach was ineffective when chatbots assisted students with "non-urgent" tasks, such as gaining access to supplemental, academic, social, and career-related support. This study demonstrates that chatbot interventions work best when they target discrete, time-sensitive, and well-defined tasks. These findings are consistent with previous text-nudge interventions in which students were less responsive to nudges related to less time-sensitive tasks such as future job prospects (CITE). It is important to note that the previously mentioned studies occurred within the GSU system. Consequently, it was unknown whether the positive effects of chatbot interventions could be replicated in institutions outside the GSU system. 

Nushatayeva et al. (2021) argue that the effectiveness of chatbot interventions are context-dependent. Nushatayeva and colleagues replicate the work of Page and Gelbach (2017) using "PeeDee," a chatbot at East Carolina University (ECU). This study provides additional evidence of treatment heterogeneity by determining for which students and under what circumstances the intervention was most effective. Researchers were primarily interested in the use of PeeDee to improve students' completion of pre-matriculation tasks and their eventual enrollment at ECU. They find no overall effect of the chatbot on college enrollment but did find an impact on loan acceptance. Students in the treatment group had an 8 percentage point increase in accepting a student loan compared to the control group. Nushatayeva et al. attribute the null overall results on college enrollment to ECU's comparatively more affluent student body. The authors did find that the chatbot increased enrollment at ECU and course enrollment by 3 percentage points, specifically for first-generation students. This positive effect is likely a result of first-generation students receiving crucial information regarding college enrollment tasks that they cannot obtain through familial support. 

Collectively, these studies demonstrate that chatbots can help to improve student success with the transition to college. Nevertheless, chatbot-based nudges are not effective in all contexts. These interventions appear most effective when chatbots assist students with time-sensitive, actionable tasks, such as clearing registration holds, rather than "non-urgent" tasks, such as searching for on-campus resources. In addition, the sender of the messages matter. Students appear most receptive to communication and messaging from a source they know and trust. Text-based nudge interventions in which the ostensive messenger is well-known to the student or affiliated with a receiving institution – such as Pounce at GSU – have relatively low opt-out rates (5 percent). In contrast, when the messaging comes from a less well-known messenger, the opt-out rates are significantly higher, as high as 25 percent. These findings are consistent with the results of the more mature literature on general nudges in college access -- context matters. Yet, little is known about the scalability of these interventions, such as at the national level, where hundreds of thousands of students are targeted.
